brokerClusterName = DefaultCluster
brokerName = broker-a
brokerId = 0
deleteWhen = 04
fileReservedTime = 48
listenPort = 10911
namesrvAddr = rocketmq-namesrv:9876
brokerRole = ASYNC_MASTER
flushDiskType = ASYNC_FLUSH
brokerIP1 =  192.168.0.111 # I have to set the broker IP to my Mac's IP address to resolve the connection issue
