spring:
  application:
    name: demo
    port: 8080

# define mysql properties here
  datasource:
    url: jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/${MYSQL_DATABASE}
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}

# define redis properties here
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      lettuce:
        pool:
          max-active: 100
          max-wait: -1ms
          max-idle: 100
          min-idle: 10

# define rocketmq properties here
  rocketmq:
    name-server: ${ROCKETMQ_NAMESRV_ADDR}
